### ISSUE TITLE
Failed to run on NixOS

### ISSUE THREAD

**Issue by matklad** [stevebob/chargrid-roguelike-tutorial-2020#2]
Hi! I've just discovered your awesome `chargrid` library, and I would love to use it for one of my pet projects. The problem is, I can't make the graphical version of chargrid to work. The error I get is

```
Failed to initialize graphical context: FailedToRequestGraphicsAdapter
```

I am on NixOS, so I suspect that this means that some dynamic library is missing or something, is there a list of runtime & compile time native dependencies somewhere?

**Comment by matklad** [comment]
https://github.com/bevyengine/bevy/pull/290/files this helped!

Here's the shell.nix which lists external dependencies:

```
with import <nixpkgs> {};
pkgs.mkShell {
  buildInputs = [
    gtk3 glib
    pkgconfig
    xorg.libX11
    vulkan-loader
  ];
  shellHook = ''
    export LD_LIBRARY_PATH="${vulkan-loader}/lib"
  '';
}
```

**Comment by gridbugs** [comment]
Thanks for raising this. Chargrid could definitely use some more documentation. Can you clarify: while in the environment described by the shell.nix you shared, were you able to run the graphical version of chargrid?

**Comment by matklad** [comment]
Yup!

![image](https://user-images.githubusercontent.com/1711539/93086973-36054b80-f698-11ea-8098-b28c3973a6f0.png)


I guess, the issue can be closed, but adding something like "you need `libvulkan.so` to run this" to chargrid's readme might be helpgul!

**Comment by gridbugs** [comment]
Glad to see you resolved it! I'll update the readme.
