### ISSUE TITLE
ai_state is referenced before being declared in Step 5

### ISSUE THREAD

**Issue by tsmaster** [stevebob/chargrid-roguelike-tutorial-2020#5]
I've been following along with the tutorial and enjoying it. In the middle of Step 5, the reader is invited to run the code and see a populated dungeon, however ai_state seems to be an undefined reference at this point. 

Perhaps move the reference to later on?

**Comment by gridbugs** [comment]
Thanks for catching this. Based on the reference implementation it looks like that variable shouldn't even be introduced yet. I've removed that line from the sample code on the page.
